# Generated by Django 3.0.2 on 2020-02-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20200224_1616'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.Role', verbose_name='Role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
