# Generated by Django 2.0 on 2020-03-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MSS', 'Mss'), ('DR', 'Dr'), ('SIR', 'Sir'), ('MADAM', 'Madam')], default='MR', max_length=10, null=True, verbose_name='Title'),
        ),
    ]
