# Generated by Django 2.0 on 2020-03-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        ('employee', '0005_remove_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reson', models.TextField(help_text='reson for no validation or cancelled?', max_length=250)),
                ('firstdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('leave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leave.Leave')),
            ],
        ),
    ]
