# Generated by Django 2.0 on 2020-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
