# Generated by Django 3.0.2 on 2020-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_role'),
        ('access', '0002_auto_20200224_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'DG'), ('2', 'COO'), ('3', 'COE'), ('4', 'DRH'), ('5', 'Manager'), ('6', 'Developper'), ('7', 'Commercial(e)'), ('8', 'Autres')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
