# Generated by Django 3.0.2 on 2020-03-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20200303_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DG', 'DG'), ('COO', 'COO'), ('COE', 'COE'), ('DRH', 'DRH'), ('Manager', 'Manager'), ('Developper', 'Developper'), ('Commercial(e)', 'Commercial(e)'), ('Autres', 'Autres')], max_length=20),
        ),
    ]
